//Bhupendra_B2C.json
var jsonString1 = `{"licenseDetails":[],"pospType":"na","allowAccess":true,"partnerType":"partner_level_1","updatedAt":"2022-11-10T12:33:41.388Z","oldAssociatedPOSPId":[],"deactivationDate":"2022-07-07T12:20:45.766Z","isActivationTriggered":null,"profileValidateSave":true,"maritalStatus":false,"oldSupervisors":[],"monthlyHealthPremium":null,"documentOwner":true,"documentNews":[{"type":"pan_card","angle":0},{"type":"profile_picture","angle":0},{"type":"CERTIFICATE","angle":0},{"type":"certificate_li","angle":0}],"referralCode":"ASH0001555","dpNo":1555,"createdAt":"2022-07-07T12:14:30.062Z","hasTMAdminUser":false,"deactivatedBy":"sachin.pangam@turtlemint.com","username":"62c6ce26ff74520001ce00ba","registeredAtIrda":false,"insuranceExperienceInYears":null,"passwordLoginEnabled":false,"primarySourceOfIncome":null,"branchCode":"1000","completed":false,"gender":"male","existingBusinessTurnover":null,"email":"ZCwdGqZ9hl5lkeh+rGA5fVNMAhmSdSE3IjHx0vk0e88jiiAj53G0IQ==","userType":"login","organisation":"ippbbc","tenantUniqueCode":"T106971412","associatePartnerStatus":false,"leadAcquisition":{"_id":"62c6ce26ff74520001ce00b9","saleStatus":"new","searchKeys":"","dpNo":1555,"createdAt":"2022-07-07T12:14:30.777Z","updatedAt":"2022-07-07T12:14:30.867Z"},"name":"bhupendra","subscriptionType":"REGULAR","isEligibleForLMS":true,"educationQualification":null,"partnerNewRefs":[],"isLoginAllowed":false,"partnerQc":{},"nomineeBankDetails":{"verified":false,"validationRetries":10},"address":{"pincode":"460551","currentPincode":"460551","city":"Betul","state":"Madhya Pradesh","displayAddress":"H No 229","country":"India"},"lmsEnrollmentDate":"2022-07-15T07:03:49.755Z","status":"verified","oldReportees":[],"acquisitionOwner":null,"salesStatus":"agreedtopartner","oldPartnerNewRefs":[],"businessVertical":"NA","monthlyMotorPremium":null,"pospDetail":{"licenseNumber":"IPPB/POSP/GI/786","licenseStartDate":"2020-07-05T18:30:00Z","expiryDate":"2023-07-05T18:30:00Z","assignAsParent":false},"lms":null,"source":"upload","_class":"com.turtlemint.mintprobe.model.partnerDetails.Partner","nameAlias1":"bhupendra wadekar","oldParents":[],"reportees":[],"_id":"62c6ce26ff74520001ce00ba","associateActive":false,"nameAlias2":"bhupendra wadekar","bankDetailsVerifier":{"verifierDpNo":0},"password":null,"pospInsurerDetails":[],"mobile":"pq7JHLUt6AlsUHOXQoQtXQ==","category":"partner","irdaiStatus":"not_checked","officeSpace":false,"verificationDate":null,"bankDetails":{"relationship":"self","verified":false,"validationRetries":10},"monthlyLifePremium":null,"transactionInfo":null,"certificateDetails":[{"pospType":"na","assignAsParent":false}],"deactivationReason":"Partner not interested to work","partnerVerifier":{"verifierDpNo":0},"businessChannel":"notset","businessProfile":{"customPosterStripId":"1c57d5d5-4121-4da3-b609-83fa70a5bc3d"},"hasNocCertificate":false}`
    

//IPPBMAH07969.JSON
var jsonString2 = `{"licenseDetails":[],"pospType":"na","allowAccess":true,"partnerType":"partner_level_1","updatedAt":"2022-11-10T07:29:29.123Z","oldAssociatedPOSPId":[],"deactivationDate":null,"isActivationTriggered":null,"profileValidateSave":true,"maritalStatus":false,"oldSupervisors":[],"monthlyHealthPremium":null,"documentOwner":true,"documentNews":[],"referralCode":"NIL0004673","dpNo":4673,"createdAt":"2022-11-09T15:42:46.111Z","hasTMAdminUser":false,"deactivatedBy":null,"username":"636bca76a77015000138e59d","registeredAtIrda":false,"insuranceExperienceInYears":null,"passwordLoginEnabled":false,"primarySourceOfIncome":null,"branchCode":"345","completed":false,"gender":null,"existingBusinessTurnover":null,"email":"NbDjxIDnnTQPK2K5VYUdB+KWvTYs7KRSWetWSQ/qojI=","userType":"login","organisation":"ippbbc","tenantUniqueCode":"IPPBMAH07969","associatePartnerStatus":false,"leadAcquisition":{"_id":"636bca76a77015000138e59c","saleStatus":"new","searchKeys":"","dpNo":4673,"createdAt":"2022-11-09T15:42:46.203Z","updatedAt":"2022-11-09T15:42:46.203Z"},"name":"nilesh netaji jadhav","subscriptionType":"REGULAR","isEligibleForLMS":null,"educationQualification":null,"partnerNewRefs":[],"isLoginAllowed":false,"partnerQc":null,"nomineeBankDetails":null,"address":null,"lmsEnrollmentDate":null,"status":"verified","oldReportees":[],"acquisitionOwner":null,"salesStatus":"new","oldPartnerNewRefs":[],"businessVertical":"NA","monthlyMotorPremium":null,"pospDetail":{"licenseNumber":"IPPB/POSP/GI/227138","licenseStartDate":"2022-11-06T18:30:00Z","expiryDate":"2022-11-05T18:30:00Z","assignAsParent":false},"lms":null,"source":"upload","_class":"com.turtlemint.mintprobe.model.partnerDetails.Partner","nameAlias1":null,"oldParents":[],"reportees":[],"_id":"636bca76a77015000138e59d","associateActive":false,"nameAlias2":null,"bankDetailsVerifier":null,"password":null,"pospInsurerDetails":[],"mobile":"KclsxeV6oXmdQpDVIBvBDQ==","category":"partner","irdaiStatus":"not_checked","officeSpace":false,"verificationDate":null,"bankDetails":null,"monthlyLifePremium":null,"transactionInfo":null,"certificateDetails":null,"deactivationReason":null,"partnerVerifier":null,"businessChannel":"notset","businessProfile":{"customPosterStripId":"1edd75d9-567c-433f-934d-c1ee55c1750b"},"hasNocCertificate":false}
`;

var jsonObject1 = JSON.parse(jsonString1);
var jsonObject2 = JSON.parse(jsonString2);

var keys = Object.keys(jsonObject1);
console.log(keys);
for (var i = 0; i < keys.length; i++) {
  var key = keys[i];
  if (jsonObject1[key] != jsonObject2[key]) {
    console.log(key + " value changed from '" + jsonObject1[key] + "' to '" + jsonObject2[key] + "'");
  }
}